# -*- coding: utf-8 -*-
"""Daya Tampung Universitas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16jCKccIaN-qZX-8BE-vxP283RF1Zwg_i
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# Import Data
---
---
"""

from google.colab import files
Ufiles=files.upload()

prodi_data = pd.read_csv(r'daftar_prodi.csv')

prodi_data.head()

from google.colab import files
Ufiles=files.upload()

univ_data = pd.read_csv('daftar_universitas.csv')

link_portal = univ_data['portal_univ']
univ_data = univ_data.drop(['portal_univ'], axis=1)

univ_data.head()

link_portal

df= univ_data.merge(prodi_data, on='kode_univ', how='inner')

df.head()

"""# Data Cleansing
---
---
"""

df = df.drop(['kode_univ'], axis=1)

df.shape

df.info()

df.isna().sum()

df.duplicated().sum()

"""# Trens Daya Tampung

---
---
"""

daya_t = df[[ 'daya_tampung_2018', 'daya_tampung_2019',
       'daya_tampung_2020', 'daya_tampung_2021', 'daya_tampung_2022','daya_tampung_2023']]
daya_t = daya_t.sum().rename('ratio').reset_index()

plt.figure(figsize=(10,6))
sns.lineplot(daya_t, x='index', y='ratio', marker ='o')
plt.xticks(rotation=45)
plt.title('Trens Daya Tampung 2018 - 2023')
plt.xlabel('Daya Tampung')
plt.show()

"""* **dari tahun 2018 mengalami penurunan ke tahun 2019 , kemudian naik stabil lagi sampai tahun 2023**

# Trens Peminat
---
---
"""

peminat_jurusan = df[[ 'peminat_2018', 'peminat_2019', 'peminat_2020', 'peminat_2021',
       'peminat_2022']]
peminat_jurusan = peminat_jurusan.sum().rename('ratio').reset_index()

plt.figure(figsize=(10,6))
sns.lineplot(peminat_jurusan, x='index', y='ratio', marker='o')
plt.xticks(rotation=45)
plt.title('Trens Peminat 2018 - 2022')
plt.xlabel('Peminat')
plt.show()

"""* **Trens peminat pada tahun 2018 ke 2019 mengalami penurunan hingga tahun 2020 , kemudian naik lagi pada tahun 2021 dan stabil sampai tahun 2022**

# Statistika Dasar
---
---
"""

df.describe().T

df.describe(include='object')

"""Universitas Pendidikan Indonesia Merupakan paling banyak peminat disini, dengn jurusan manajemen tingkat Sarjana

# Top 10 Universitas, Nama Prodi & Jenjang
---
---
"""

top10 = df['nama_univ'].value_counts().rename('Peminat').reset_index()
top10=top10.head(10)

plt.figure(figsize=(10,6))
sns.barplot(data=top10, x='index', y='Peminat')
plt.xticks(rotation=90)
plt.title('Top 10 Peminat Universitas')
plt.xlabel('Nama Universitas')
plt.tight_layout()
plt.grid(axis='y', linestyle='--')
plt.show()

"""* **Peminat Universitas pendidikan Indonesia adalah yang menempati peringkat pertama dan disusul oleh Univ Haluoleo dan ke 3 Univ Brawijaya**"""

top10_prodi = df['nama_prodi'].value_counts().rename('Peminat').reset_index()
top10_prodi = top10_prodi.head(10)

plt.figure(figsize=(10,6))
sns.barplot(data=top10_prodi, x='index', y='Peminat')
plt.xticks(rotation=90)
plt.title('Top 10 Peminat Prodi')
plt.xlabel('Nama Prodi')
plt.tight_layout()
plt.grid(axis='y', linestyle='--')
plt.show()

"""* **Prodi Manajemen Merupan peringkat pertama dengan peminat dan disusul oleh Akuntansi kemudian Matematika**"""

jenjang = df['jenjang'].value_counts()

explodes =0.5,0.8
plt.pie(jenjang.values, labels=  jenjang.index, autopct='%1.1f%%', startangle =45, explode =explodes)
plt.title('Peminat Jenjang')
plt.show()

"""* **Berdasarkan pie plot Hampir semua peminat di jurusan Sarjana dengan perbandingan 10 : 1**

# Universitas dengan Nama Prodi dan Daya Tampung
---
---
"""

from ipywidgets import interact

daya_tampung = df[['daya_tampung_2018', 'daya_tampung_2019',
       'daya_tampung_2020', 'daya_tampung_2021', 'daya_tampung_2022','daya_tampung_2023']]

@interact
def plot_data(nama_univ=df['nama_univ'].unique()):
    nama_univ1 = df[df['nama_univ'] == nama_univ]
    f, ax = plt.subplots(len(daya_tampung.columns), 1, figsize=(30, 35))

    for i, column in enumerate(daya_tampung.columns):
        sns.set(style='whitegrid')
        sns.barplot(data=nama_univ1, y=column, x='nama_prodi', ax=ax[i], palette='husl')
        ax[i].tick_params(axis='x', rotation=90)
        ax[i].set_title(f'Nama Prodi dengan {column}')

    plt.tight_layout()
    plt.show()

"""# Universitas dengan Nama Prodi dan Peminat
---

---
"""

peminat = df[['peminat_2018', 'peminat_2019', 'peminat_2020', 'peminat_2021',
       'peminat_2022']]

@interact
def plot_data(nama_univ=df['nama_univ'].unique()):
    nama_univ1 = df[df['nama_univ'] == nama_univ]
    f, ax = plt.subplots(len(peminat.columns), 1, figsize=(15, 30))

    for i, column in enumerate(peminat.columns):
        sns.set(style='whitegrid')
        sns.barplot(data=nama_univ1, y=column, x='nama_prodi', ax=ax[i], palette='husl')
        ax[i].tick_params(axis='x', rotation=90)
        ax[i].set_title(f'Nama Prodi dengan {column}')

    plt.tight_layout()
    plt.show()